posts/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('', views.last_posts_view, name='last-posts'),
    path('home/', views.home, name='home'),
    path('like', views.like, name='like'),
    path('republish', views.republish_view, name='republish'),
    path('createpost', views.post_create_view, name='create-post'),
    path('detail/<int:post_id>/create-comment', views.create_comment, name='create-comment'),
    path('detail/<int:post_id>/', views.post_detail_view, name='detail-post'),
    path('hashtag/<str:name>/', views.hashtags, name='hashtags')
]

socialNetwork/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
    path('profiles/', include('profiles.urls')),
    path('controller/', include('control.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Hashtag(models.Model):
    name = models.CharField(max_length=25)


class PostComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='comments')
    post = models.ForeignKey("Post", on_delete=models.CASCADE)
    comment = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def serialize(self):
        return {
            "id": self.id,
            "comment": self.comment,
            "username": self.user.username,
        }


class PostLike(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey("Post", on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)


class Post(models.Model):
    parent = models.ForeignKey("self", null=True,
                               on_delete=models.CASCADE, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name="posts")
    likes = models.ManyToManyField(User, related_name='post_user',
                                   blank=True, through=PostLike)
    content = models.TextField(blank=True, null=True)
    image = models.FileField(upload_to='images/', blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    hashtag = models.ManyToManyField(Hashtag, blank=True,
                                     related_name='post_hashtag')

    class Meta:
        ordering = ['-id']

    @property
    def is_repost(self):
        return self.parent != None

    def serialize(self):
        data = {
            "id": self.id,
            "content": self.content,
            "likes": PostLike.objects.filter(post=self).count(),
            "username": self.user.username,
            "name": self.user.get_full_name(),
            "profile_img": self.user.profile.profileImage.url,
            "parent": self.parent.serialize() if self.parent else None
        }
        if self.image:
            data["post_img"] = self.image.url
        return data

posts/forms.py
from django import forms
from .models import Post


class CreatePost(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea, required=True)
    image = forms.FileField(required=False)

    class Meta:
        model = Post
        fields = ['content', 'image']

posts/views.py
from django.core.paginator import Paginator
from django.db.models import Count
from django.http import HttpResponse, JsonResponse, Http404
from django.contrib.auth.decorators import login_required, user_passes_test
from django.shortcuts import render
from .models import Post, PostComment, Hashtag
from .forms import CreatePost
import json


def last_posts_view(request):
    qs = Post.objects.all().order_by("-timestamp")
    posts = [x.serialize() for x in qs]
    paginator = Paginator(posts, 50)
    top_hashtags = Hashtag.objects.annotate(
        num_posts=Count('post_hashtag')).order_by('-num_posts')[:5]
    page_number = request.GET.get('page')
    posts = paginator.get_page(page_number)
    context = {
        'posts': posts,
        'type': 'last_posts',
        'top_hashtags': top_hashtags
    }
    return render(request, 'posts/posts.html', context)


@login_required(login_url='/accounts/login/')
def home(request):
    user = request.user
    qs = user.following.all()
    followed_users = [x.user.id for x in qs]
    followed_users.append(user.id)
    posts = Post.objects.filter(
        user__id__in=followed_users).order_by("-timestamp")[:60]
    posts = [x.serialize() for x in posts]
    context = {
        'posts': posts,
        'type': 'home'
    }
    return render(request, 'posts/posts.html', context)


@login_required(login_url='/accounts/login/')
def like(request):
    user = request.user
    body_unicode = request.body.decode('utf-8')
    body = json.loads(body_unicode)
    post_id = body['post_id']
    post = Post.objects.filter(id=post_id).first()
    if post:
        post_likes = post.likes.all()
        if user in post_likes:
            post.likes.remove(user)
        else:
            post.likes.add(user)
    else:
        return HttpResponse(False)
    likes = post.likes.all().count()
    return HttpResponse(likes)


@login_required(login_url='/accounts/login/')
def post_create_view(request, *args, **kwargs):
    user = request.user
    if request.method == 'POST':
        form = CreatePost(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = user
            post.save()
            tags = [tag.strip("#") for tag in post.content.split() if tag.startswith("#")]
            for tag in tags:
                qr = Hashtag.objects.filter(name=tag)
                if qr.exists():
                    tagobj = qr.first()
                else:
                    tagobj = Hashtag.objects.create(name=tag)
                post.hashtag.add(tagobj)
            data = post.serialize()
            return JsonResponse(data=data)
    return


@login_required(login_url='/accounts/login/')
def republish_view(request):
    action_user = request.user
    body_unicode = request.body.decode('utf-8')
    body = json.loads(body_unicode)
    target_id = body['post_id']
    target_post = Post.objects.filter(id=target_id)
    if not target_post.exists():
        return Http404
    target_post = target_post.first()
    if target_post.parent:
        target_post = target_post.parent

    post = Post.objects.create(user=action_user, parent=target_post)
    parent_post = post.parent.serialize()
    data = {
        'id': post.id,
        'username': action_user.username,
        'name': action_user.get_full_name(),
        'profile_img': action_user.profile.profileImage.url,
        'parent': parent_post,
    }
    return JsonResponse(data=data)


def post_detail_view(request, post_id):
    post = Post.objects.filter(id=post_id)
    if not post:
        return Http404
    qs = PostComment.objects.filter(post=post.first()).order_by("-timestamp")
    comments = [x.serialize() for x in qs]
    post = post.first().serialize()

    context = {
        'post': post,
        'comments': comments
    }
    return render(request, 'posts/detail.html', context=context)


@login_required(login_url='/accounts/login/')
def create_comment(request, post_id):
    user = request.user
    body_unicode = request.body.decode('utf-8')
    body = json.loads(body_unicode)
    content = body['content']
    post_id = body['post_id']
    if not content or not post_id:
        return JsonResponse(data='', status=404)
    post = Post.objects.filter(id=post_id)
    if not post:
        return JsonResponse(data='', status=404)

    comment = PostComment.objects.create(user=user,
                                         comment=content,
                                         post=post.first())
    comment.save()
    comment = comment.serialize()
    return JsonResponse(data=comment)


@login_required(login_url='/accounts/login/')
def hashtags(request, name):
    tag = Hashtag.objects.filter(name=name)
    top_hashtags = Hashtag.objects.annotate(
        num_posts=Count('post_hashtag')).order_by('-num_posts')[:5]
    posts = []
    if tag.exists():
        tagobj = tag.first()
        posts = Post.objects.filter(hashtag=tagobj).order_by("-timestamp")
        posts = [x.serialize() for x in posts]
        paginator = Paginator(posts, 50)
        page_number = request.GET.get('page')
        posts = paginator.get_page(page_number)
    context = {
        'posts': posts,
        'type': 'hashtag',
        'name': name,
        'top_hashtags': top_hashtags
    }
    return render(request, 'posts/posts.html', context)

templates/posts/detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
{% if post.parent %}
    <div class='col-12 col-md-10 mx-auto border rounded py-3 mb-4 carousel slide post' id='post-{{ post.id }}'>
        <img class="rounded-circle article-img avatar" src="{{ post.profile_img }}" alt="">
            <h5><a href="{% url 'profile' post.username %}">{{ post.name }}</a></h5>
        <em dir="ltr"><a href="{% url 'profile' post.username %}">@{{ post.username }}</a></em>
        <div class='col-12 col-md-10 mx-auto border rounded py-3 mb-4 carousel slide' id='post-{{ post.parent.id }}'>
            <img class="rounded-circle article-img avatar" src="{{ post.parent.profile_img }}" alt="">
            <h5><a href="{% url 'profile' post.parent.username %}">{{ post.parent.name }}</a></h5>
            <em dir="ltr"><a href="{% url 'profile' post.parent.username %}">@{{ post.parent.username }}</a></em>
            <div class="ms-2 mt-4">
                <p>{{ post.parent.content|linebreaks }}</p>
            </div>
            {% if post.parent.post_img %}
                <img src="{{ post.parent.post_img }}" alt="" style="width: inherit; max-height: 300px">
            {% endif %}
            <a href="{% url 'detail-post' post.parent.id %}" class="next carousel-control-next fa fa-angle-left"></a>
        </div>
        <p class='ms-sm-5'>
            <button class='btn btn-primary btn-sm' onclick='handleLikeBtn({{ post.id }})'>
                <span class='fa fa-thumbs-up'></span>
                <span id='postlike-{{ post.id }}'>{{ post.likes }}</span>
            </button>
{#            <button class='btn btn-primary btn-sm' onclick='handleRepublishBtn({{ post.id }})'>#}
{#                <span class='fa fa-retweet'></span>#}
{#            </button>#}
        </p>
    </div>
{% else %}
    <div class='col-12 col-md-10 mx-auto border rounded py-3 mb-4 carousel slide post' id='post-{{ post.id }}'>
        <img class="rounded-circle article-img avatar" src="{{ post.profile_img }}" alt="">
            <h5><a href="{% url 'profile' post.username %}">{{ post.name }}</a></h5>
        <em dir="ltr"><a href="{% url 'profile' post.username %}">@{{ post.username }}</a></em>
        <div class="ms-3">
            <p>{{ post.content|linebreaks }}</p>
        </div>
        {% if post.post_img %}
            <img src="{{ post.post_img }}" alt="" style="width: inherit; max-height: 300px">
        {% endif %}
        <p class="ms-sm-5">
            <button class='btn btn-primary btn-sm' onclick="handleLikeBtn({{ post.id }})">
                <span class="fa fa-thumbs-up"></span>
                <span id="postlike-{{ post.id }}">{{ post.likes }}</span>
            </button>
{#            <button class='btn btn-primary btn-sm' onclick="handleRepublishBtn({{ post.id }})">#}
{#                <span class="fa fa-retweet"></span>#}
{#            </button>#}
        </p>
    </div>

{% endif %}
<div class="mx-auto col-10">
    <form class="form" id="comment-create-form" method="POST" action="comment">
        {% csrf_token %}
        <div class="d-none alert alert-danger" id="post-create-form-error"></div>
        <textarea required="required" class="form-control" name="content" placeholder="نظر شما"></textarea>
        <button type="submit" class="btn btn-primary ms-2 mt-2 mb-3" >ارسال نظر</button>
    </form>
</div>



<div class="row" id="comments">
    {% for comment in comments %}
            <div class='col-12 col-md-10 mx-auto border border-3 rounded py-3 mb-4 bg-white'>
                <em dir="ltr"><a href="{% url 'profile' comment.username %}">@{{ comment.username }}</a></em>
                <span>{{ comment.comment }}</span>
            </div>
    {% endfor %}
</div>



{% endblock %}


{% block js %}
<script>

function getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        const cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            const cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}

function formatComment(content, username){
    const userInfo = '<em dir="ltr"><a href="' + username + '/profiles">@' + username + '</a></em>'
    const comment = '<span>' + content + '</span>'
    const result =  '<div class="col-12 col-md-10 mx-auto border border-3 rounded py-3 mb-4 bg-white">' + userInfo + comment + '</div>'
    return result
}


const commentsContainerElement = document.getElementById("comments")


function handleCreateComment(event){
    event.preventDefault()
    const csrftoken = getCookie('csrftoken');
    const myForm = event.target
    const myFormData = new FormData(myForm)
    const content = myFormData.get("content")
    const post_id = {{ post.id }}
    const data = {
        'content': content,
        'post_id': post_id
    }
    fetch('create-comment', {
        method: "POST",
        body: JSON.stringify(data),
        headers: {
            "Content-type": "application/json; charset=UTF-8",
            'X-CSRFToken': csrftoken,
        },
        dataType: 'json'
    }).then(response => response.json())
        .then(response =>{
            const rescontent = response.comment
            const username = response.username
            const newCommentElement = formatComment(rescontent, username)
            const ogHtml = commentsContainerElement.innerHTML
            commentsContainerElement.innerHTML = newCommentElement + ogHtml
            myForm.reset()
        }).catch(error => window.location.replace("/accounts/login/"));
}

const commentCreateFormEl = document.getElementById("comment-create-form");
commentCreateFormEl.addEventListener("submit", handleCreateComment);


</script>

<script src="/static/js/getCookie.js"></script>
<script src="/static/js/postHandler.js"></script>


{% endblock %}

templates/posts/post-controller.html
{% extends 'base.html' %}

{% block content %}
    <div class="row col-9" id="posts">
        {% for post in posts %}
            {% if post.parent %}
                <div class='col-12 col-md-10 mx-auto border rounded py-3 mb-4 bg-white carousel slide' id='post-{{ post.id }}'>
                    <img class="rounded-circle article-img avatar" src="{{ post.profile_img }}" alt="">
                    {% if post.name %}
                        <h5><a href="{% url 'profile' post.username %}">{{ post.name }}</a></h5>
                    {% endif %}
                    <em dir="ltr"><a href="{% url 'profile' post.username %}">@{{ post.username }}</a></em>
                    <div class='col-12 col-md-10 mx-auto border rounded py-3 mb-4 carousel slide' id='post-{{ post.parent.id }}'>
                        <img class="rounded-circle article-img avatar" src="{{ post.parent.profile_img }}" alt="">
                        {% if post.parent.name %}
                            <h5><a href="{% url 'profile' post.parent.username %}">{{ post.parent.name }}</a></h5>
                        {% endif %}
                        <em dir="ltr"><a href="{% url 'profile' post.parent.username %}">@{{ post.parent.username }}</a></em>
                        <p>{{ post.parent.content }}</p>
                        {% if post.parent.post_img %}
                            <img src="{{ post.parent.post_img }}" alt="" style="width: inherit; max-height: 300px">
                        {% endif %}
                        <a href="{% url 'detail-post' post.parent.id %}" class="bg-success carousel-control-next fa fa-angle-left" style="font-size:32px; width: 10%;"></a>
                    </div>
                    <p class='btn-group'>
                        <button class='btn btn-primary btn-sm' onclick='handleLikeBtn({{ post.id }})'>
                            <span class='fa fa-thumbs-up'></span>
                            <span id='postlike-{{ post.id }}'>{{ post.likes }}</span>
                        </button>
                        <button class='btn btn-primary btn-sm' onclick='handleRepublishBtn({{ post.id }})'>
                            <span class='fa fa-retweet'></span>
                        </button>
                        <button class='btn btn-primary btn-sm' onclick='handleRepublishBtn({{ post.id }})'>
                            <span class='fas fa-comment-dots'></span>
                        </button>
                    </p>
                    <a href="{% url 'detail-post' post.id %}" class="bg-success carousel-control-next fa fa-angle-left" style="font-size:32px; width: 10%;"></a>
                </div>
            {% else %}
                <div class='col-12 col-md-10 mx-auto border rounded py-3 mb-4 carousel slide' id='post-{{ post.id }}'>
                    <img class="rounded-circle article-img avatar" src="{{ post.profile_img }}" alt="">
                    {% if post.name %}
                        <h5><a href="{% url 'profile' post.username %}">{{ post.name }}</a></h5>
                    {% endif %}
                    <em dir="ltr"><a href="{% url 'profile' post.username %}">@{{ post.username }}</a></em>
                    <p>{{ post.content }}</p>
                    {% if post.post_img %}
                        <img src="{{ post.post_img }}" alt="" style="width: inherit; max-height: 300px">
                    {% endif %}
                    <p class="btn-group">
                        <button class='btn btn-primary btn-sm' onclick="handleLikeBtn({{ post.id }})">
                            <span class="fa fa-thumbs-up"></span>
                            <span id="postlike-{{ post.id }}">{{ post.likes }}</span>
                        </button>
                        <button class='btn btn-primary btn-sm' onclick="handleRepublishBtn({{ post.id }})">
                            <span class="fa fa-retweet"></span>
                        </button>
                        <button class='btn btn-primary btn-sm'>
                            <span class='fas fa-comment-dots'></span>
                        </button>
                    </p>
                    <a href="{% url 'detail-post' post.id %}" class="bg-success carousel-control-next fa fa-angle-left" style="font-size:32px; width: 10%;" ></a>
                </div>

            {% endif %}
        {% endfor %}
    </div>

{% endblock %}
{% block js %}

{% endblock %}

templates/posts/posts.html
{% extends 'base.html' %}


{% block home %}
    {% if type == 'home' %}active{% endif %}
{% endblock %}
{% block last_post %}
    {% if type == 'last_posts' %}active{% endif %}
{% endblock %}


{% block header %}
{% if type == 'home' %}
    <div id="create-post">
    <div class="container pt-2 pb-2">
        <div class="row col-7 col-sm mt-3 mx-auto">
            <div class="mx-auto col-10">
                <form class="form" id="post-create-form" method="POST" action="create-post">
                    {% csrf_token %}
                    <textarea id="id_content" required="required" class="form-control" name="content" placeholder="Your content"></textarea>
                    <div class="file-upload">
                        <div class="image-upload-wrap">
                            <input class="file-upload-input" id="id_image" type='file' onchange="readURL(this);" accept="image/*" />
                            <div class="drag-text">
                                <h3>عکس را بکشید <br>یا ضربه بزنید</h3>
                            </div>
                        </div>
                        <div class="file-upload-content">
                            <img class="file-upload-image" src="#" alt="your image" />
                            <div class="image-title-wrap">
                                <button type="button" onclick="removeUpload()" class="remove-image">X</button>
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary mt-1 mx-auto" >ارسال</button>
                </form>
            </div>
        </div>
    </div>
    </div>
{% endif %}
{% endblock %}
{% block sidebar %}
    {% if type != 'home' %}
    <div class="col-2 ms-5 hashtags d-none d-sm-block position-fixed">
    <p class="p-1">هشتگها</p>
        <ol style="list-style-type: none;">
            {% for hashtag in top_hashtags %}
                <a href="{% url 'hashtags' hashtag.name %}">
                    <li>#{{ hashtag.name }} <em>{{ hashtag.num_posts }}</em></li>
                </a>
            {% endfor %}
        </ol>
    </div>
    {% endif %} 
{% endblock %}


{% block content %}
    {% if type == 'hashtag' %}
        <h4>#{{ name }}</h4>
    {% endif %}
<div class="row mt-3" id="posts">
    {% for post in posts %}
        {% if post.parent %}
            <div class='col-12 col-md-10 mx-auto border rounded py-3 mb-4 carousel slide post' id='post-{{ post.id }}'>
                <img class="rounded-circle article-img avatar" src="{{ post.profile_img }}" alt="">
                <h5><a href="{% url 'profile' post.username %}">{{ post.name }}</a></h5>
                <em dir="ltr"><a href="{% url 'profile' post.username %}">@{{ post.username }}</a></em>
                <div class='col-12 col-md-10 mx-auto border rounded py-3 mb-4 carousel slide' id='post-{{ post.parent.id }}'>
                    <img class="rounded-circle article-img avatar" src="{{ post.parent.profile_img }}" alt="">
                    <h5><a href="{% url 'profile' post.parent.username %}">{{ post.parent.name }}</a></h5>
                    <em dir="ltr"><a href="{% url 'profile' post.parent.username %}">@{{ post.parent.username }}</a></em>
                    <div class="ms-2 mt-4">
                        <p>{{ post.parent.content|linebreaks }}</p>
                    </div>
                    {% if post.parent.post_img %}
                        <img src="{{ post.parent.post_img }}" alt="" style="width: inherit; max-height: 300px">
                    {% endif %}
                    <a href="{% url 'detail-post' post.parent.id %}" class="next carousel-control-next fa fa-angle-left"></a>
                </div>
                <div class="col-12">
                    <p class='btn-group mt-1'>
                    <button class='btn btn-primary btn-sm' onclick='handleLikeBtn({{ post.id }})'>
                        <span class='fa fa-thumbs-up'></span>
                        <span id='postlike-{{ post.id }}'>{{ post.likes }}</span>
                    </button>
                    <button class='btn btn-primary btn-sm' onclick='handleRepublishBtn({{ post.id }})'>
                        <span class='fa fa-retweet'></span>
                    </button>
                    </p>
                    <a href="{% url 'detail-post' post.id %}" class="next carousel-control-next fa fa-angle-left"></a>
                </div>
            </div>
        {% else %}
            <div class='col-12 col-md-10 mx-auto border rounded py-3 mb-4 carousel slide post' id='post-{{ post.id }}'>
                <img class="rounded-circle article-img avatar" src="{{ post.profile_img }}" alt="">
                <h5><a href="{% url 'profile' post.username %}">{{ post.name }}</a></h5>
                <em dir="ltr"><a href="{% url 'profile' post.username %}">@{{ post.username }}</a></em>
                <div class="ms-2 mt-4">
                    <p>{{ post.content|linebreaks }}</p>
                </div>
                {% if post.post_img %}
                    <img src="{{ post.post_img }}" alt="" style="width: inherit; max-height: 300px">
                {% endif %}
                <div class="col-12">
                    <p class="btn-group mt-1">
                        <button class='btn btn-primary btn-sm' onclick="handleLikeBtn({{ post.id }})">
                            <span class="fa fa-thumbs-up"></span>
                            <span id="postlike-{{ post.id }}">{{ post.likes }}</span>
                        </button>
                        <button class='btn btn-primary btn-sm' onclick="handleRepublishBtn({{ post.id }})">
                            <span class="fa fa-retweet"></span>
                        </button>
                    </p>
                </div>
                <a href="{% url 'detail-post' post.id %}" class="next carousel-control-next fa fa-angle-left"></a>
            </div>

        {% endif %}
    {% endfor %}
</div>
{% if type != 'home' %}
    <div class="navbar-nav pagination mx-auto mb-5">
        <ul class="mx-auto navbar" style="list-style-type: none;">
            {% if posts.has_previous %}
                <li class="page-item"><a href="?page={{ posts.previous_page_number }}" class="page-link">قبلی</a></li>
            {% else %}
                <li class="page-item disabled"><a href="#" class="page-link">قبلی</a></li>
            {% endif %}
            {% if posts.has_next %}
                <li class="page-item"><a href="?page={{ posts.next_page_number }}" class="page-link">بعدی</a></li>
            {% else %}
                <li class="page-item disabled"><a href="#" class="page-link">بعدی</a></li>
            {% endif %}
        </ul>
    </div>
{% endif %}
{% endblock content %}
{% block js %}
    <script src="/static/js/getCookie.js"></script>
    <script src="/static/js/postHandler.js"></script>
{% if type == 'home' %}
    <script src="/static/js/imageinput.js"></script>
    <script src="/static/js/handleCreatePost.js"></script>
    <script src="/static/js/jquery.js"></script>
{% endif %}

{% endblock js %}